"""Regression tests for the queue-recommendations apply path (issue #2137).

``agent_loop._append_queue_recommendations`` writes generated ``T-2026-NNNN`` tasks
into ``tasks/queue.md`` only when apply is requested. The PRODUCTION queue.md carries a
``## Examples`` marker, so generated TABLE ROWS land just before it. The pre-existing
fixture in ``test_agent_loop.py`` has no such marker, so it only exercised the
marker-ABSENT (table-row silent-drop) branch and never asserted a row landed. These
tests lock the marker-PRESENT row-landing path that production actually uses, plus
idempotency (re-apply => no duplicate rows) and graceful dedup. They underpin the
opt-in ``make 시작 START_QUEUE_RECOMMENDATIONS_APPLY=1`` auto-grow wired in the same
change (see test_sijak_queue_recommendations_optin.py).
"""

from __future__ import annotations

import re

from scripts import agent_loop

QUEUE_WITH_MARKER = """\
# Task queue

| Order | ID | Status | Owner role | Why ready |
| --- | --- | --- | --- | --- |
| 5 | `T-2026-0005` | `ready` | executor | seed task |

## Examples

- example content
"""

QUEUE_WITHOUT_MARKER = """\
# Task queue

| Order | ID | Status | Owner role | Why ready |
| --- | --- | --- | --- | --- |
| 5 | `T-2026-0005` | `ready` | executor | seed task |
"""


def _rec(title, *, status="backlog", owner_role="executor", trigger="unit-test trigger"):
    return agent_loop.QueueRecommendation(
        title=title,
        status=status,
        priority="P2",
        owner_role=owner_role,
        lane="serial",
        goal=f"Goal for {title}",
        trigger=trigger,
        acceptance=("ships behind opt-in",),
        validation=("bash scripts/test.sh",),
    )


def _write_queue(repo_root, text):
    queue = repo_root / "tasks" / "queue.md"
    queue.parent.mkdir(parents=True, exist_ok=True)
    queue.write_text(text, encoding="utf-8")
    return queue


def test_apply_lands_table_rows_and_details_when_marker_present(tmp_path):
    queue = _write_queue(tmp_path, QUEUE_WITH_MARKER)
    recs = [_rec("Alpha auto-grow task"), _rec("Beta auto-grow task")]

    applied = agent_loop._append_queue_recommendations(recommendations=recs, repo_root=tmp_path)

    assert [a["task_id"] for a in applied] == ["T-2026-0006", "T-2026-0007"]
    text = queue.read_text(encoding="utf-8")
    # Table ROWS landed — the production path the marker-less fixture never exercised.
    assert re.search(
        r"^\| 6 \| `T-2026-0006` \| `backlog` \| executor \| generated by queue-recommendations;",
        text,
        re.MULTILINE,
    )
    assert re.search(r"^\| 7 \| `T-2026-0007` \|", text, re.MULTILINE)
    # Detail sections landed.
    assert "## T-2026-0006 — Alpha auto-grow task" in text
    assert "## T-2026-0007 — Beta auto-grow task" in text
    # Rows/details are inserted before the Examples marker (appended to the table).
    assert text.index("T-2026-0006") < text.index("## Examples")


def test_reapply_is_idempotent_no_duplicate_rows(tmp_path):
    queue = _write_queue(tmp_path, QUEUE_WITH_MARKER)
    recs = [_rec("Alpha auto-grow task"), _rec("Beta auto-grow task")]

    first = agent_loop._append_queue_recommendations(recommendations=recs, repo_root=tmp_path)
    assert len(first) == 2
    rows_first = queue.read_text(encoding="utf-8").count("generated by queue-recommendations;")

    second = agent_loop._append_queue_recommendations(recommendations=recs, repo_root=tmp_path)
    assert second == []
    rows_second = queue.read_text(encoding="utf-8").count("generated by queue-recommendations;")
    assert rows_first == rows_second == 2


def test_apply_skips_titles_already_in_queue(tmp_path):
    _write_queue(tmp_path, QUEUE_WITH_MARKER)
    agent_loop._append_queue_recommendations(
        recommendations=[_rec("Alpha auto-grow task")], repo_root=tmp_path
    )
    # Second batch mixes a duplicate title with a fresh one — only the fresh task lands.
    applied = agent_loop._append_queue_recommendations(
        recommendations=[_rec("Alpha auto-grow task"), _rec("Delta fresh task")],
        repo_root=tmp_path,
    )
    assert [a["title"] for a in applied] == ["Delta fresh task"]


def test_marker_absent_appends_details_but_drops_rows_documented_gap(tmp_path):
    # DOCUMENTED current behavior: without a `## Examples` marker the detail sections are
    # appended but the table rows are silently dropped. Hardening that drop is an explicit
    # non-goal of issue #2137; pinning today's behavior makes any future change deliberate.
    queue = _write_queue(tmp_path, QUEUE_WITHOUT_MARKER)
    applied = agent_loop._append_queue_recommendations(
        recommendations=[_rec("Gamma auto-grow task")], repo_root=tmp_path
    )
    assert len(applied) == 1
    text = queue.read_text(encoding="utf-8")
    assert "## T-2026-0006 — Gamma auto-grow task" in text  # detail present
    assert "generated by queue-recommendations;" not in text  # row dropped (the gap)
